import {TitleIDPair} from "./TitleIDPair";

export enum ALIGNMENT {
    LAWFUL_GOOD = 1,
    NEUTRAL_GOOD = 2,
    CHAOTIC_GOOD = 3,
    LAWFUL_NEUTRAL = 4,
    TRUE_NEUTRAL = 5,
    CHAOTIC_NEUTRAL = 6,
    LAWFUL_EVIL = 7,
    NEUTRAL_EVIL = 8,
    CHAOTIC_EVIL = 9,
}

export const ALIGNMENT_STRINGS: {[key: string]: string} = {
    LAWFUL_GOOD: "Lawful Good",
    NEUTRAL_GOOD: "Neutral Good",
    CHAOTIC_GOOD: "Chaotic Good",
    LAWFUL_NEUTRAL: "Lawful Neutral",
    TRUE_NEUTRAL: "True Neutral",
    CHAOTIC_NEUTRAL: "Chaotic Neutral",
    LAWFUL_EVIL: "Lawful Evil",
    NEUTRAL_EVIL: "Neutral Evil",
    CHAOTIC_EVIL: "Chaotic Evil",
}

export const ALIGNMENT_DATA: {[key: string]: TitleIDPair} = {
    LAWFUL_GOOD: {title: ALIGNMENT_STRINGS.LAWFUL_GOOD, ID: ALIGNMENT.LAWFUL_GOOD},
    NEUTRAL_GOOD: {title: ALIGNMENT_STRINGS.NEUTRAL_GOOD, ID: ALIGNMENT.NEUTRAL_GOOD},
    CHAOTIC_GOOD: {title: ALIGNMENT_STRINGS.CHAOTIC_GOOD, ID: ALIGNMENT.CHAOTIC_GOOD},
    LAWFUL_NEUTRAL: {title: ALIGNMENT_STRINGS.LAWFUL_NEUTRAL, ID: ALIGNMENT.LAWFUL_NEUTRAL},
    TRUE_NEUTRAL: {title: ALIGNMENT_STRINGS.TRUE_NEUTRAL, ID: ALIGNMENT.TRUE_NEUTRAL},
    CHAOTIC_NEUTRAL: {title: ALIGNMENT_STRINGS.CHAOTIC_NEUTRAL, ID: ALIGNMENT.CHAOTIC_NEUTRAL},
    LAWFUL_EVIL: {title: ALIGNMENT_STRINGS.LAWFUL_EVIL, ID: ALIGNMENT.LAWFUL_EVIL},
    NEUTRAL_EVIL: {title: ALIGNMENT_STRINGS.NEUTRAL_EVIL, ID: ALIGNMENT.NEUTRAL_EVIL},
    CHAOTIC_EVIL: {title: ALIGNMENT_STRINGS.CHAOTIC_EVIL, ID: ALIGNMENT.CHAOTIC_EVIL},
}