export const ITEM = {
    COMPONENT_POUCH: 1,
    ARCANE_FOCUS: 2,
    DUNGEONEERS_PACK: 3,
    EXPLORERS_PACK: 4,
}

export const ITEM_STRINGS = {
    COMPONENT_POUCH: "Component Pouch",
    ARCANE_FOCUS: "Arcane Focus",
    DUNGEONEERS_PACK: "Dungeoneers Pack",
    EXPLORERS_PACK: "Explorers Pack",
}

export const ITEM_DATA = {
    COMPONENT_POUCH: {title: ITEM_STRINGS.COMPONENT_POUCH, value: ITEM.COMPONENT_POUCH},
    ARCANE_FOCUS: {title: ITEM_STRINGS.ARCANE_FOCUS, value: ITEM.ARCANE_FOCUS},
    DUNGEONEERS_PACK: {title: ITEM_STRINGS.DUNGEONEERS_PACK, value: ITEM.DUNGEONEERS_PACK},
    EXPLORERS_PACK: {title: ITEM_STRINGS.EXPLORERS_PACK, value: ITEM.EXPLORERS_PACK},
}