export enum WEAPON {
    // SIMPLE MELEE
    CLUB = 1,
    DAGGER = 2,
    GREATCLUB = 3,
    HANDAXE = 4,
    JAVELIN = 5,
    LIGHTHAMMER = 6,
    MACE = 7,
    QUARTERSTAFF = 8,
    SICKLE = 9,
    SPEAR = 10,

    // SIMPLE RANGED
    CROSSBOW_LIGHT = 11,
    DART = 12,
    SHORTBOW = 13,
    SLING = 14,

    // MARTIAL MELEE
    BATTLEAXE = 15,
    FLAIL = 16,
    GLAIVE = 17,
    GREATAXE = 18,
    GREATSWORD = 19,
    HALBERD = 20,
    LANCE = 21,
    LONGSWORD = 22,
    MAUL = 23,
    MORNINGSTAR = 24,
    PIKE = 25,
    RAPIER = 26,
    SCIMITAR = 27,
    SHORTSWORD = 28,
    TRIDENT = 29,
    WARPICK = 30,
    WARHAMMER = 31,
    WHIP = 32,

    // MARTIAL RANGED
    BLOWGUN = 33,
    CROSSBOW_HAND = 34,
    CROSSBOW_HEAVY = 35,
    LONGBOW = 36,
    NET = 37,
}

export const WEAPON_STRINGS = {
    // SIMPLE MELEE
    CLUB: "Club",
    DAGGER: "Dagger",
    GREATCLUB: "Greatclub",
    HANDAXE: "Handaxe",
    JAVELIN: "Javelin",
    LIGHTHAMMER: "Lighthammer",
    MACE: "Mace",
    QUARTERSTAFF: "Quarterstaff",
    SICKLE: "Sickle",
    SPEAR: "Spear",

    // SIMPLE RANGED
    CROSSBOW_LIGHT: "Crossbow Light",
    DART: "Dart",
    SHORTBOW: "Shortbow",
    SLING: "Sling",

    // MARTIAL MELEE
    BATTLEAXE: "Battleaxe",
    FLAIL: "Flail",
    GLAIVE: "Glaive",
    GREATAXE: "Greataxe",
    GREATSWORD: "Greatsword",
    HALBERD: "Halberd",
    LANCE: "Lance",
    LONGSWORD: "Longsword",
    MAUL: "Maul",
    MORNINGSTAR: "Morningstar",
    PIKE: "Pike",
    RAPIER: "Rapier",
    SCIMITAR: "Scimitar",
    SHORTSWORD: "Shortsword",
    TRIDENT: "Trident",
    WARPICK: "Warpick",
    WARHAMMER: "Warhammer",
    WHIP: "Whip",

    // MARTIAL RANGED
    BLOWGUN: "Blowgun",
    CROSSBOW_HAND: "Crossbow Hand",
    CROSSBOW_HEAVY: "Crossbow Heavy",
    LONGBOW: "Longbow",
    NET: "Net",
}

export const WEAPON_LIST = {
    // SIMPLE MELEE
    CLUB: {title: WEAPON_STRINGS.CLUB, value: WEAPON.CLUB},
    DAGGER: {title: WEAPON_STRINGS.DAGGER, value: WEAPON.DAGGER},
    GREATCLUB: {title: WEAPON_STRINGS.GREATCLUB, value: WEAPON.GREATCLUB},
    HANDAXE: {title: WEAPON_STRINGS.HANDAXE, value: WEAPON.HANDAXE},
    JAVELIN: {title: WEAPON_STRINGS.JAVELIN, value: WEAPON.JAVELIN},
    LIGHTHAMMER: {title: WEAPON_STRINGS.LIGHTHAMMER, value: WEAPON.LIGHTHAMMER},
    MACE: {title: WEAPON_STRINGS.MACE, value: WEAPON.MACE},
    QUARTERSTAFF: {title: WEAPON_STRINGS.QUARTERSTAFF, value: WEAPON.QUARTERSTAFF},
    SICKLE: {title: WEAPON_STRINGS.SICKLE, value: WEAPON.SICKLE},
    SPEAR: {title: WEAPON_STRINGS.SPEAR, value: WEAPON.SPEAR},

    // SIMPLE RANGED
    CROSSBOW_LIGHT: {title: WEAPON_STRINGS.CROSSBOW_LIGHT, value: WEAPON.CROSSBOW_LIGHT},
    DART: {title: WEAPON_STRINGS.DART, value: WEAPON.DART},
    SHORTBOW: {title: WEAPON_STRINGS.SHORTBOW, value: WEAPON.SHORTBOW},
    SLING: {title: WEAPON_STRINGS.SLING, value: WEAPON.SLING},

    // MARTIAL MELEE
    BATTLEAXE: {title: WEAPON_STRINGS.BATTLEAXE, value: WEAPON.BATTLEAXE},
    FLAIL: {title: WEAPON_STRINGS.FLAIL, value: WEAPON.FLAIL},
    GLAIVE: {title: WEAPON_STRINGS.GLAIVE, value: WEAPON.GLAIVE},
    GREATAXE: {title: WEAPON_STRINGS.GREATAXE, value: WEAPON.GREATAXE},
    GREATSWORD: {title: WEAPON_STRINGS.GREATSWORD, value: WEAPON.GREATSWORD},
    HALBERD: {title: WEAPON_STRINGS.HALBERD, value: WEAPON.HALBERD},
    LANCE: {title: WEAPON_STRINGS.LANCE, value: WEAPON.LANCE},
    LONGSWORD: {title: WEAPON_STRINGS.LONGSWORD, value: WEAPON.LONGSWORD},
    MAUL: {title: WEAPON_STRINGS.MAUL, value: WEAPON.MAUL},
    MORNINGSTAR: {title: WEAPON_STRINGS.MORNINGSTAR, value: WEAPON.MORNINGSTAR},
    PIKE: {title: WEAPON_STRINGS.PIKE, value: WEAPON.PIKE},
    RAPIER: {title: WEAPON_STRINGS.RAPIER, value: WEAPON.RAPIER},
    SCIMITAR: {title: WEAPON_STRINGS.SCIMITAR, value: WEAPON.SCIMITAR},
    SHORTSWORD: {title: WEAPON_STRINGS.SHORTSWORD, value: WEAPON.SHORTSWORD},
    TRIDENT: {title: WEAPON_STRINGS.TRIDENT, value: WEAPON.TRIDENT},
    WARPICK: {title: WEAPON_STRINGS.WARPICK, value: WEAPON.WARPICK},
    WARHAMMER: {title: WEAPON_STRINGS.WARHAMMER, value: WEAPON.WARHAMMER},
    WHIP: {title: WEAPON_STRINGS.WHIP, value: WEAPON.WHIP},

    // MARTIAL RANGED
    BLOWGUN: {title: WEAPON_STRINGS.BLOWGUN, value: WEAPON.BLOWGUN},
    CROSSBOW_HAND: {title: WEAPON_STRINGS.CROSSBOW_HAND, value: WEAPON.CROSSBOW_HAND},
    CROSSBOW_HEAVY: {title: WEAPON_STRINGS.CROSSBOW_HEAVY, value: WEAPON.CROSSBOW_HEAVY},
    LONGBOW: {title: WEAPON_STRINGS.LONGBOW, value: WEAPON.LONGBOW},
    NET: {title: WEAPON_STRINGS.NET, value: WEAPON.NET},
}

export const getSimpleWeaponsList = () => {
    return [
        WEAPON_LIST.CLUB,
        WEAPON_LIST.DAGGER,
        WEAPON_LIST.GREATCLUB,
        WEAPON_LIST.HANDAXE,
        WEAPON_LIST.JAVELIN,
        WEAPON_LIST.LIGHTHAMMER,
        WEAPON_LIST.MACE,
        WEAPON_LIST.QUARTERSTAFF,
        WEAPON_LIST.SICKLE,
        WEAPON_LIST.SPEAR,
    ]
}
export const getSimpleWeaponsStrings = () => {
    return [
        WEAPON_STRINGS.CLUB,
        WEAPON_STRINGS.DAGGER,
        WEAPON_STRINGS.GREATCLUB,
        WEAPON_STRINGS.HANDAXE,
        WEAPON_STRINGS.JAVELIN,
        WEAPON_STRINGS.LIGHTHAMMER,
        WEAPON_STRINGS.MACE,
        WEAPON_STRINGS.QUARTERSTAFF,
        WEAPON_STRINGS.SICKLE,
        WEAPON_STRINGS.SPEAR,
    ]
}